# Generated by Django 4.2.5 on 2023-10-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название пункта меню.', max_length=100)),
                ('url_name', models.CharField(blank=True, help_text='Имя URL-адреса для пункта меню (необязательно).', max_length=100, null=True)),
                ('url', models.CharField(blank=True, help_text='URL-адрес для пункта меню (необязательно).', max_length=100, null=True)),
                ('menu_name', models.CharField(blank=True, help_text='Название меню, к которому относится пункт меню (необязательно).', max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский пункт меню, если он есть (необязательно).', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'MenuItem',
                'verbose_name_plural': 'MenuItems',
            },
        ),
    ]
